services:
  - type: web
    name: tradingview-webhook
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python copy_db_once.py && gunicorn app:app"
